### ISSUE TITLE
Raspberry Pi2 is actually able to transcode streams

### ISSUE THREAD

**Issue by bradleybossard** [greensheep/plex-server-docker-rpi#1]
Hi greensheep,

Thanks for creating this repo.  I too have been interested in Docker and Plex on the Pi2, and recently came across this blog post on the awesome HTPC Guides blog

http://www.htpcguides.com/fix-plex-server-is-not-powerful-enough-on-raspberry-pi-2/

which has a method for tricking ARM hardware so it will transcode.  Apply this hack to your Dockerfile, I have now successfully created a Docker image which is able to transcode up to three streams simultaneously on the RPi2.  Thought you might be interested and I can send you a PR if want to update your repo.

https://github.com/bradleybossard/plex-server-docker-rpi

b.

**Comment by greensheep** [comment]
Hi Bradley,

I tried your repo and unfortunately couldn't get transcoding to work. I did a fresh install of the latest hypriot image (0.6.1 Hector) and created a brand new plex library.

For me, a H.265 (HEVC) source played in Chrome will play for a few seconds then buffer for a few minutes and eventually fail with "there was a problem playing this item".

With H.264, the video will use the direct play feature of Plex because Chrome supports this format.  I see in the server (in the activity -> now playing tab) that Plex is transcoding, but it's just the audio.

If I turn off direct play/stream (under "Show Advanced" in the Web -> Player settings) and basically enforce transcoding, I can't play anything - the CPU on the Pi maxes out and I get endless buffering on the player.

The same files will transcode perfectly if I use a Plex server running on my desktop machine which leads me to believe that the Pi2 is still not powerful enough.

Tom

**Comment by bradleybossard** [comment]
Hmm.... Interesting Tom, thanks for the info.  I do not claim to be a video expert, all I know is the movie described in following screenshot did not play for me when I used your repo, but after I added the changes to mine, I was able to play it in a Plex web browser on Chrome and two Rokus simutaneously, the entire movie from start to finish without buffering, but maybe it isn't the ultimate torture test.

I am going to scrub through my library and put together a small batch of video files of the hardest things to transcode, what do you suggest I look for?

Another experiment I want to try today is getting Docker running on my Orange Pi PC

http://www.orangepi.org/orangepipc/

which has better specs than the Raspberry Pi 2 (and only costs $15).  There is a Debian Wheezy build available for it, and following these instructions, I think it might be possible.  I'll let you know what happens.

http://blog.hypriot.com/post/family_arm_hardware_for_docker_more_children/

![image](https://cloud.githubusercontent.com/assets/125572/11918773/fe88cb26-a6f3-11e5-893b-d3399a506d51.png)

**Comment by bradleybossard** [comment]
Oh yeah, one other thing I should mention is, I am reading the movies files off a Samba server in my network, not off the SD card on the Pi itself.  Not sure if that would introduce a bottleneck or not that could cause the buffering.

**Comment by greensheep** [comment]
I'm no expert on video either but it seems to me that it really depends on what your player supports.  By default, Plex will only use transcoding as a last resort if your player doesn't support the source format.

The players I have available (Apple TV 4th gen, iPhone, Nexus tablet, Chrome browser) all support H.264 and the vast majority of my media happens to be in this format so it direct plays.

My guess with your example video is that possibly the audio needed to be transcoded and not the video.  The hack you applied tricked the player into telling the server to transcode and it was ok because audio is less CPU intensive to transcode.

I would look for any media you have that isn't "Codec: H.264" and see what happens.

Let me know how it goes with your Orange Pi, the CPU specs are definitely better than the Pi but still falls short of what's recommended by Plex: https://support.plex.tv/hc/en-us/articles/200375666-Stand-Alone-Server.

I'm working on adding an NFS server in a linked container so the Plex data dir can be easily shared on the network. I have an external HD mounted into `/home/pi/plex/data` so it's an easy way of adding new media and the server is completely standalone on the Pi.
