### ISSUE TITLE
Update to latest version of Plex

### ISSUE THREAD

**Issue by jordancrawford** [greensheep/plex-server-docker-rpi#2]
The current image runs 0.9.12.19.

I did a re-build and everything seems to work fine with 0.9.14.6. (Plex server version history: https://plex.tv/downloads/1/archive)
Could you do a re-build and push to Docker Hub?

Also, it doesn't seem to detect when the version gets out of date which is weird? Likely to do with the version in the apt-get repo rather than the Docker image.

**Comment by greensheep** [comment]
I've done a quick rebuild and pushed the latest version to the docker hub - you should be able to pull it now.

My guess is that in order for Plex to show there's a new version available, `apt-get update` needs to be run inside the container (I haven't had chance to try yet).  I plan on experimenting with the official binaries provided by Plex rather than using the dev2day package so maybe that will help.
